const $=id=>document.getElementById(id);
const DEFAULT_DOMAINS=['localhost','127.0.0.1'];
let domains=[], active=null, mode='observe';
function log(s){$('log').textContent += new Date().toLocaleTimeString()+' '+s+'\n';$('log').scrollTop=$('log').scrollHeight;}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function hostname(url){try{return new URL(url).hostname.toLowerCase()}catch{return ''}}
function allowed(host){return domains.some(d=>d.startsWith('*.')?(host===d.slice(2)||host.endsWith('.'+d.slice(2))):host===d)}
function renderDomains(){$('domains').innerHTML=domains.map(d=>'<code>• '+esc(d)+'</code>').join('<br>')||'<span class="muted">ยังไม่มีโดเมน</span>';}
async function load(){const x=await chrome.storage.local.get({domains:DEFAULT_DOMAINS,mode:'observe',audit:[]});domains=x.domains;mode=x.mode;$('mode').value=mode;renderDomains();$('modePill').textContent=mode.toUpperCase();}
function save(){return chrome.storage.local.set({domains,mode})}
async function tab(){const t=(await chrome.tabs.query({active:true,currentWindow:true}))[0];active=t;if(!t){$('tab').textContent='ไม่พบแท็บ';return}const h=hostname(t.url||'');$('tab').innerHTML='<b>'+esc(t.title||'(ไม่มีชื่อ)')+'</b><br><span class="muted">'+esc(t.url||'')+'</span><br><span class="'+(allowed(h)?'ok':'warn')+'">'+(allowed(h)?'โดเมนอยู่ใน allowlist':'โดเมนยังไม่อยู่ใน allowlist')+'</span>';}
async function read(){await tab();if(!active||!active.id){log('หยุด: ไม่พบแท็บ');return}const h=hostname(active.url||'');if(!allowed(h)){log('หยุด: '+h+' ไม่อยู่ใน allowlist');$('result').innerHTML='<span class="warn">ต้องเพิ่มโดเมนนี้ใน allowlist ก่อน จึงจะอ่านได้</span>';return}log('ขออ่านแท็บโดย user gesture: '+h);try{const out=await chrome.scripting.executeScript({target:{tabId:active.id},func:collectPage});const p=out?.[0]?.result;if(!p)throw Error('ไม่มีผลลัพธ์');const injection=detectInjection(p.text);const err=p.errors.length?'<br><span class="warn">พบข้อความคล้าย error: '+p.errors.slice(0,3).map(esc).join(' · ')+'</span>':'';const inj=injection?'<div class="danger" style="margin-top:7px">พบข้อความที่อาจเป็น prompt injection ในหน้าเว็บ — จะไม่ทำตาม</div>':'';$('result').innerHTML='<span class="ok">อ่านสำเร็จ</span><br>หัวข้อ: '+esc(p.title)+'<br>ข้อความที่อ่าน: '+p.text.length.toLocaleString()+' ตัวอักษร<br>หัวข้อย่อย: '+p.headings.slice(0,5).map(esc).join(' · ')||'-';$('result').innerHTML+=err+inj;renderPlan(p,injection);log('อ่านสำเร็จ: '+p.text.length+' chars'+(injection?' / injection warning':''));}catch(e){$('result').innerHTML='<span class="bad">อ่านไม่ได้: '+esc(e.message)+'</span>';log('ล้มเหลว: '+e.message)}}
function collectPage(){const text=(document.body?.innerText||'').slice(0,20000);const headings=[...document.querySelectorAll('h1,h2,h3')].map(x=>x.innerText.trim()).filter(Boolean).slice(0,20);const errors=[...document.querySelectorAll('[role=alert],.error,.errors,[class*=error]')].map(x=>x.innerText.trim()).filter(Boolean).slice(0,10);return{title:document.title,url:location.href,text,headings,errors}}
function detectInjection(t){return /(ignore (all|any|previous)|system prompt|reveal.*password|send.*secret|disable.*security|bypass.*approval)/i.test(t||'')}


async function makePlan(){const goal=$('goal').value.trim();if(!goal){log('ยังไม่ได้ระบุเป้าหมาย');return}try{const r=await fetch('http://127.0.0.1:8787/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal})});const j=await r.json();$('plans').innerHTML=(j.plan||[]).map(x=>'<div class="plan"><b>'+x.step+'. '+esc(x.role)+'</b> — '+esc(x.action)+' · '+esc(x.decision)+'</div>').join('');$('result').innerHTML='<span class="ok">Structured Plan พร้อม</span><br>Approval required: '+j.approvalRequired+'<br>Blocked: '+j.blocked;log('สร้าง plan: '+(j.blocked?'มี blocked action':'พร้อมตรวจต่อ'))}catch(e){log('planner error: '+e.message)}}

async function runSafeTests(){try{const r=await fetch('http://127.0.0.1:8787/execute',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'run_tests'})});const j=await r.json();$('result').innerHTML=j.ok?'<span class="ok">Safe Tests ผ่าน</span><br><pre style="white-space:pre-wrap;font-size:10px">'+esc(j.stderr||j.stdout||'')+'</pre>':'<span class="bad">Safe Tests ไม่ผ่าน</span><br>'+esc(j.reason||j.error||'');log('run_tests: '+(j.ok?'PASS':'FAIL'))}catch(e){$('result').innerHTML='<span class="warn">Local Operator ยังไม่ทำงาน</span>';log('run_tests error: '+e.message)}}

async function analyzeLocal(){await tab();if(!active||!active.id){log('หยุด: ไม่พบแท็บ');return}const h=hostname(active.url||'');if(!allowed(h)){log('หยุด: '+h+' ไม่อยู่ใน allowlist');return}try{const out=await chrome.scripting.executeScript({target:{tabId:active.id},func:collectPage});const p=out?.[0]?.result;const r=await fetch('http://127.0.0.1:8787/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const j=await r.json();$('result').innerHTML='<span class="ok">Local Operator วิเคราะห์แล้ว</span><br>ข้อความหลัง redaction: '+j.redactedTextLength+' ตัวอักษร<br>หัวข้อ: '+(j.headings||[]).map(esc).join(' · ')+'<br>'+(j.signals?.promptInjection?'<span class="bad">หยุด: พบ prompt injection</span>':'<span class="ok">ไม่พบ prompt injection จากกฎพื้นฐาน</span>')+'<br>'+(j.signals?.riskTerms?.length?'<span class="warn">คำเสี่ยง: '+j.signals.riskTerms.map(esc).join(', ')+'</span>':'');$('plans').innerHTML=(j.plan||[]).map(x=>'<div class="plan"><b>'+x.step+'. '+esc(x.actor)+'</b> — '+esc(x.action)+' · '+esc(x.approval)+'</div>').join('');log('Local Operator สำเร็จ: analysis_only')}catch(e){$('result').innerHTML='<span class="warn">Local Operator ยังไม่ทำงาน — ใช้ analyzer ในส่วนขยายแทน</span>';log('Local Operator ใช้งานไม่ได้: '+e.message)}}

function renderPlan(p,injection){$('plans').innerHTML='<div class="plan"><b>1. Observer</b> — อ่าน DOM/ข้อความโดยไม่ส่งข้อมูลออก</div><div class="plan"><b>2. Verifier</b> — ตรวจหัวข้อและ error ที่มองเห็น</div><div class="plan"><b>3. Action policy</b> — โหมด '+mode+'; '+(mode==='auto-safe'?'จำกัด sandbox/localhost':'ไม่มี action อัตโนมัติ')+'</div>'+(injection?'<div class="plan bad"><b>หยุด</b> — แยกเนื้อหาเว็บเป็น untrusted data</div>':'');}
$('read').onclick=read;$('backend').onclick=analyzeLocal;$('tests').onclick=runSafeTests;$('makePlan').onclick=makePlan;$('mark').onclick=async()=>{await tab();if(!active?.id)return;try{await chrome.scripting.executeScript({target:{tabId:active.id},func:()=>{const x=document.createElement('div');x.textContent='Browser Copilot: อ่านแท็บแล้ว — ไม่มีการคลิกหรือส่งข้อมูล';Object.assign(x.style,{position:'fixed',zIndex:2147483647,top:'14px',right:'14px',padding:'10px 14px',background:'#102347',color:'#fff',border:'1px solid #6d9aff',borderRadius:'8px',font:'13px system-ui'});document.documentElement.appendChild(x);setTimeout(()=>x.remove(),3000)}});log('แสดงสถานะบนแท็บแล้ว')}catch(e){log('ไม่สามารถแสดงสถานะ: '+e.message)}};
$('add').onclick=async()=>{let d=$('domain').value.trim().toLowerCase().replace(/^https?:\/\//,'').replace(/\/.*$/,'');if(!/^(\*\.)?[a-z0-9.-]+$/.test(d)){log('โดเมนไม่ถูกต้อง');return}if(!domains.includes(d)){domains.push(d);await save();renderDomains();log('เพิ่ม allowlist: '+d)}$('domain').value='';tab()};$('mode').onchange=async e=>{mode=e.target.value;$('modePill').textContent=mode.toUpperCase();await save();log('เปลี่ยนโหมด: '+mode)};
load().then(tab);